name = "shouna"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "shouna-db"
database_id = "9853e8ce-641c-4478-b5b8-696b09907ef2"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "shouna-photos"


